# Generated by Django 4.1.2 on 2023-05-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuestionario',
            old_name='questions',
            new_name='question',
        ),
    ]
