# Generated by Django 4.1.2 on 2023-05-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0003_rename_question_cuestionario_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionario',
            name='questions',
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question10',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question11',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question12',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question13',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question14',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question15',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question16',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question17',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question18',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question6',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question7',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question8',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='question9',
            field=models.TextField(default=''),
        ),
    ]
