# Generated by Django 4.1.2 on 2023-05-27 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='type',
            new_name='type_user',
        ),
    ]
