# Generated by Django 4.2.5 on 2023-09-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(null=True)),
                ('pregunta1', models.TextField(null=True)),
                ('pregunta2', models.TextField(null=True)),
                ('pregunta3', models.TextField(null=True)),
                ('pregunta4', models.TextField(null=True)),
                ('pregunta5', models.TextField(null=True)),
                ('pregunta6', models.TextField(null=True)),
                ('pregunta7', models.TextField(null=True)),
                ('pregunta8', models.TextField(null=True)),
                ('pregunta9', models.TextField(null=True)),
                ('pregunta10', models.TextField(null=True)),
                ('pregunta11', models.TextField(null=True)),
                ('pregunta12', models.TextField(null=True)),
                ('pregunta13', models.TextField(null=True)),
                ('pregunta14', models.TextField(null=True)),
                ('pregunta15', models.TextField(null=True)),
                ('pregunta16', models.TextField(null=True)),
                ('pregunta17', models.TextField(null=True)),
                ('pregunta18', models.TextField(null=True)),
                ('pregunta19', models.TextField(null=True)),
                ('pregunta20', models.TextField(null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cuestionarios',
            },
        ),
    ]
