version: '3'

services:
  postgresql_plaza:
    container_name: "postgres_pw"
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: u_plaza_web
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test_plaza_web
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  plazaweb:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/plaza_web_paradigma/
    ports:
      - "9009:8000"
    depends_on:
      - postgresql_plaza

volumes:
  postgresql-data:


