# Generated by Django 4.1.2 on 2023-06-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='dni',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='last_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
