# Generated by Django 4.1.2 on 2023-06-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0002_trabajador_dni_trabajador_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
