# Generated by Django 4.1.2 on 2023-05-26 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_trabajo', '0003_rename_service_type_plantrabajo_tipo_servicio'),
        ('trabajador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('laborable', models.BooleanField(default=True)),
                ('presente', models.BooleanField(default=False)),
                ('id_plan_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_trabajo.plantrabajo')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajador.trabajador')),
            ],
        ),
    ]
