# Generated by Django 4.1.2 on 2023-06-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacio_trabajo', '0002_espaciotrabajo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaciotrabajo',
            name='address',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
