# Generated by Django 4.1.2 on 2023-09-15 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidente', '0001_initial'),
        ('plan_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='id_plan_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_trabajo.plantrabajo'),
        ),
    ]
