# Generated by Django 4.1.2 on 2023-09-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='espacio_trabajo_images/')),
                ('address', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
