# Generated by Django 4.2.5 on 2023-09-22 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('finalizado', 'Finalizado'), ('informado', 'Informado')], default='new', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='incidente_images/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'incidentes',
            },
        ),
    ]
