# Generated by Django 4.1.2 on 2023-05-21 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('espacio_trabajo', '0001_initial'),
        ('cooperativa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('tipo_servicio', models.TextField()),
                ('id_cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.cooperativa')),
                ('id_espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacio_trabajo.espaciotrabajo')),
                ('id_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
