# Generated by Django 4.1.2 on 2023-08-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_trabajo', '0003_rename_service_type_plantrabajo_tipo_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantrabajo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
