version: '3'

services:
  postgresql_plaza_dj:
    container_name: "postgres_pw_dj"
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: u_plaza_web
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test_plaza_web
    ports:
      - "5432:5432"
    volumes:
      - ../data/db:/var/lib/postgresql/data
    networks:
      - plazaweb

  plazaweb:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py collectstatic --no-input && gunicorn config.wsgi:application --bind 0.0.0.0:8000"  # sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../:/plaza_web_paradigma/
      - static_volume:/plaza_web_paradigma/static
      - static_media:/plaza_web_paradigma/media
    depends_on:
      - postgresql_plaza_dj
    networks:
      - plazaweb

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - plazaweb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/plaza_web_paradigma/static
      - static_media:/plaza_web_paradigma/media
    networks:
      - plazaweb

volumes:
  # postgresql-data:
  static_volume:
  static_media:


networks:
  plazaweb:
    driver: bridge
