version: '3'

services:
  postgresql_plaza_dj:
    container_name: "postgres_pw_dj"
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: u_plaza_web
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test_plaza_web
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - plazaweb
  plazaweb:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../:/plaza_web_paradigma/
    ports:
      - "8000:8000"
    depends_on:
      - postgresql_plaza_dj
    networks:
      - plazaweb

volumes:
  postgresql-data:


networks:
  plazaweb:
    driver: bridge
