version: '3'

services:
  postgresql_plaza_dj_dev:
    container_name: "postgres_pw_dj_dev"
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: u_plaza_web
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test_plaza_web
    volumes:
      - ../data_dev/db:/var/lib/postgresql/data
    networks:
      - plazaweb_dev
    ports:
      - 7000:5432

  plazaweb_dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata seed_data/users_types_seed.json && python manage.py loaddata seed_data/user.seed.json && python manage.py loaddata seed_data/feriado.seed.json && python manage.py loaddata seed_data/trabajador.seed.json && python manage.py loaddata seed_data/cooperativa.seed.json && python manage.py loaddata seed_data/espacio_trabajo.seed.json && python manage.py collectstatic --no-input && python manage.py runserver"
    volumes:
      - ../:/plaza_web_paradigma/
    ports:
      - 8000:8000
    depends_on:
      - postgresql_plaza_dj_dev
    networks:
      - plazaweb_dev

networks:
  plazaweb_dev:
    driver: bridge
