# Generated by Django 4.1.2 on 2023-05-21 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_trabajo', '0003_rename_service_type_plantrabajo_tipo_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('finalized', 'Finalizado'), ('informed', 'Informado')], default='new', max_length=20)),
                ('id_plan_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_trabajo.plantrabajo')),
            ],
        ),
    ]
