# Generated by Django 4.1.2 on 2023-05-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='state',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('finalizado', 'Finalizado'), ('informado', 'Informado')], default='new', max_length=20),
        ),
    ]
