# Generated by Django 4.1.2 on 2023-06-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0002_alter_incident_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='incidente_images/'),
        ),
    ]
