# Generated by Django 4.1.2 on 2023-06-27 19:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0003_incident_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, upload_to='incident_images/'), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='incident',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='incident',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
