# Generated by Django 4.1.2 on 2023-05-31 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0005_alter_cuestionario_question1_and_more'),
        ('respuesta_cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestacuestionario',
            name='id_cuestionario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cuestionario.cuestionario'),
        ),
    ]
