# Generated by Django 4.2.5 on 2023-09-22 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperativas', '0001_initial'),
        ('espacios_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('tipo_servicio', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativas.cooperativa')),
                ('id_espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios_trabajo.espaciotrabajo')),
            ],
            options={
                'db_table': 'planes_trabajo',
            },
        ),
    ]
