# Generated by Django 4.1.2 on 2023-06-03 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_type', '0001_initial'),
        ('users', '0005_rename_type_customuser_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_type.usertype'),
        ),
    ]
