# Generated by Django 4.2.5 on 2023-09-22 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperativas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('documento_nro', models.IntegerField(unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cooperativas.cooperativa')),
            ],
            options={
                'db_table': 'trabajadores',
            },
        ),
    ]
