# Generated by Django 4.1.2 on 2023-05-25 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabajador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_result', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], default='malo', max_length=20)),
                ('evaluation_type', models.CharField(choices=[('uniforme', 'Uniforme'), ('epp', 'EPP'), ('herramientas', 'Herramientas')], default='Uniforme', max_length=20)),
                ('id_coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajador.trabajador')),
            ],
        ),
    ]
