# Generated by Django 4.2.5 on 2023-09-22 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluacion_trabajador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciontrabajador',
            name='id_coordinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluaciontrabajador',
            name='id_trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador'),
        ),
    ]
