# Generated by Django 4.1.2 on 2023-05-31 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_trabajo', '0003_rename_service_type_plantrabajo_tipo_servicio'),
        ('cuestionario', '0005_alter_cuestionario_question1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionDesempeño',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('fecha', models.DateField()),
                ('ubicacion', models.TextField()),
                ('id_cuestionario', models.ForeignKey(
                    default=None, on_delete=django.db.models.deletion.CASCADE, to='cuestionario.cuestionario')),
                ('id_plan_trabajo', models.ForeignKey(
                    default=None, on_delete=django.db.models.deletion.CASCADE, to='plan_trabajo.plantrabajo')),
            ],
        ),
    ]
