# Generated by Django 4.2.5 on 2023-09-22 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperativas', '0001_initial'),
        ('espacios_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionDesempeño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('latitud', models.TextField()),
                ('longitud', models.TextField()),
                ('id_cooperativa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cooperativas.cooperativa')),
                ('id_espacio_trabajo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='espacios_trabajo.espaciotrabajo')),
            ],
            options={
                'db_table': 'evaluaciones_desempeño',
            },
        ),
    ]
