# Generated by Django 4.2.5 on 2023-09-22 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planes_trabajo', '0001_initial'),
        ('evaluaciones_desempeño', '0001_initial'),
        ('respuestas_cuestionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='id_plan_trabajo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='planes_trabajo.plantrabajo'),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='id_respuesta_cuestionario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='respuestas_cuestionarios.respuestacuestionario'),
        ),
    ]
