# Generated by Django 4.2.5 on 2023-09-22 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones_desempeño', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='id_supervisor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
