# Generated by Django 4.1.2 on 2023-05-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0002_rename_questions_cuestionario_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuestionario',
            old_name='question',
            new_name='questions',
        ),
    ]
