# Generated by Django 4.1.2 on 2023-06-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0005_alter_cuestionario_question1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
