# Generated by Django 4.1.2 on 2023-09-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0006_cuestionario_latitud_cuestionario_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionario',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='cuestionario',
            name='longitud',
        ),
    ]
