# Generated by Django 4.2.5 on 2023-09-22 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0001_initial'),
        ('planes_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('laborable', models.BooleanField(default=True)),
                ('presente', models.BooleanField(default=False)),
                ('id_plan_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes_trabajo.plantrabajo')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador')),
            ],
            options={
                'db_table': 'planillas_trabajo',
            },
        ),
    ]
