# Generated by Django 4.1.2 on 2023-09-15 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantrabajo',
            name='id_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
