# Generated by Django 4.1.2 on 2023-05-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantrabajo',
            old_name='tipo_servicio',
            new_name='service_type',
        ),
    ]
