# Generated by Django 4.1.2 on 2023-05-21 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_trabajo', '0002_rename_tipo_servicio_plantrabajo_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantrabajo',
            old_name='service_type',
            new_name='tipo_servicio',
        ),
    ]
